baseURL = 'https://pranj.al/'
languageCode = 'en-us'
title = 'Pranjal Vachaspati'
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
description = "Pranjal Vachaspati"
copyright = "Copyright © 2020 Pranjal Vachaspati"
dark = "auto"
highlight = true

[menu]
[[menu.main]]
identifier = "posts"
name = "posts"
title = "posts"
url = "/"
weight = 10

[[menu.main]]
identifier = "about"
name = "about"
title = "about"
url = "/about/"
weight = 20

[permalinks]
posts = "/:title/"

[markup.goldmark.renderer]
# Allows HTML in Markdown
unsafe = true