name: Upload Website

on:
  push:
    branches:
    - main
  workflow_dispatch:



jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.119.0'
        # extended: true

    - name: Build
      run: hugo --minify && find
      working-directory: ./www

    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args:  --follow-symlinks --delete --exclude '.git/*' #--acl public-read
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: www/public
